export const profileData = [
  {
    firstName: 'Norma',
    lastName: 'Byers',
    title: 'Loving pet sitter',
    description: 'Dog sitting,cat sitting, pocket pet and bird care',
    rate: '$14',
    city: 'Vancouver',
  },
  {
    firstName: 'Michael',
    lastName: 'Carnahan',
    title: 'Dog care helper',
    description: 'I have had dogs and pets for most of my life',
    rate: '15',
    city: 'Langley',
  },
  {
    firstName: 'Jessica',
    lastName: 'Pearson',
    title: 'Professional dog trainer',
    description: 'I would love to work with your dog',
    rate: '$25',
    city: 'Toronto',
  },
  {
    firstName: 'Charless',
    lastName: 'Compton',
    title: 'Passionate pet sitter',
    description: 'I provide dog walking and pet sitting services',
    rate: '$16',
    city: 'Brampton',
  },
  {
    firstName: 'Charlotte',
    lastName: 'Butler',
    title: 'Animal lover',
    description: 'I am dog walker that cant want to to meet your pet',
    rate: '$17',
    city: 'Calgary',
  },
  {
    firstName: 'Joan ',
    lastName: 'Blakeney',
    title: 'Loving pet walker',
    description: 'I have experience working and walking with dogs',
    rate: '$13',
    city: 'Surrey',
  },
];
